//This file is generated by VisualGDB and is used to get accurate IntelliSense
#pragma once
#include <Arduino.h>

#define SYSPROGS_ARDUINO_EXPAND_GENERATED_PROTOTYPES \
	void PrintMsg(String X); \
	int LoadingKey(); \
	void Loadapp(); \
	void setup(); \
	void loop(); \

